name: 'Hello World'
description: 'Proof of concept action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'Stefan'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}